apiVersion: v1
kind: Pod
metadata:
  name: cvmfs-atlas-20220301
spec:
  containers:
   - name: idle
     image: busybox
     imagePullPolicy: IfNotPresent
     command: [ "/bin/sh", "-c", "trap : TERM INT; (while true; do sleep 1000; done) & wait" ]
     volumeMounts:
       - name: atlas-20220301
         mountPath: /atlas.cern.ch
  volumes:
   - name: atlas-20220301
     persistentVolumeClaim:
       claimName: cvmfs-atlas-20220301
