# Create PersistentVolume and PersistentVolumeClaim for CVMFS automounts.

apiVersion: v1
kind: PersistentVolume
metadata:
  # PV name contains namespace name of its target PVC so that we can distiguish it easier.
  name: cvmfs-atlas-20220301-default
spec:
  csi:
    driver: cvmfs.csi.cern.ch
    volumeHandle: cvmfs-atlas-20220301-default

    volumeAttributes:
      repository: atlas.cern.ch
      sharedMountID: atlas-20220301
      clientConfig: |
        CVMFS_SERVER_URL=http://cvmfs-stratum-one.cern.ch/cvmfs/atlas.cern.ch
        CVMFS_KEYS_DIR=/etc/cvmfs/keys/cern.ch
        CVMFS_HTTP_PROXY=DIRECT
        CVMFS_REPOSITORY_DATE=2022-03-01T00:00:00Z

  accessModes:
  - ReadOnlyMany
  capacity:
    # Volume size value has no effect and is ignored
    # by the driver, but must be non-zero.
    storage: 1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-atlas-20220301
  namespace: default
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1
  # volumeName must match the name we have set in the PersistentVolume defined above.
  volumeName: cvmfs-atlas-20220301-default
  # Storage class name must be set to an empty string "".
  storageClassName: ""
