name: Docker

on:
  push:
    branches: [devel,master]
  pull_request:
    branches: [devel,master]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image
        run: |
          cd test/common/container
          docker compose up --build -d cvmfs-dev

      - name: Build CVMFS
        run: |
          docker exec -u sftnight -t cvmfs-dev bash -c \
            "cmake -S /home/sftnight/cvmfs -B /tmp/cvmfs-build -D EXTERNALS_PREFIX=/tmp/cvmfs-ext -D BUILD_SHRINKWRAP=ON"

      - name: Install CVMFS
        run: |
          docker exec -u sftnight -t cvmfs-dev bash -c \
            "cd /tmp/cvmfs-build && make && sudo make install"

      - name: Setup CVMFS
        run: |
          docker exec -u sftnight -t cvmfs-dev /bin/bash -c "sudo cvmfs_config setup"
          docker exec -u sftnight -t cvmfs-dev /bin/bash -c "sudo cvmfs_config chksetup" || exit 1

      - name: Run quick test suite
        run: |
          docker exec -u sftnight -t cvmfs-dev bash -c \
            "cd /home/sftnight/cvmfs/test && \
            CVMFS_TEST_USER=sftnight ./run.sh /tmp/cvmfs-test.log -s 'quick' ./src/0* ./src/1*"

      - name: Archive logs
        if: ${{ always () }}
        run: |
          docker cp cvmfs-dev:/tmp/cvmfs-test.log /tmp/cvmfs-test.log

      - name: Upload logs as artifact
        if: ${{ always () }}
        uses: actions/upload-artifact@v2
        with: 
          name: CVMFS test logs
          path: /tmp/cvmfs-test.log

